@rootUrl = http://localhost:8020

###check if the server is live
GET {{rootUrl}}

###creating a new user
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName": "bibek",
    "lName": "malla",
    "email": "bbekhamal26@gmail.com",
    "phone":"1234",
    "password": "Bibek@9"

}

###activating a user
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{

    "sessionId": "68ad78084e6244cf3e91a518",
    "t": "4ea7c9f6-657c-4e60-90aa-eb264652da7b"
}

###login the user
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"bbekhamal26@gmail.com",
    "password":"Bibek@9"
}

###get the user profile
GET {{rootUrl}}/api/v1/user/profile 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiZWtoYW1hbDI2QGdtYWlsLmNvbSIsImlhdCI6MTc1NjgxMzIwMiwiZXhwIjoxNzU2ODE0MTAyfQ.8C6TNKI19xRA4T7wXAkbVtC7MRD7GMMrjemSuzTxS_I


###WE WILL RENEW THE JWT HERE 
GET {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiZWtoYW1hbDI2QGdtYWlsLmNvbSIsImlhdCI6MTc1NjgxMzE2NywiZXhwIjoxNzU5NDA1MTY3fQ.viiXCERrH22NO0KuquUgQx4JQWsbsB91J90iMerSq4o

###logging out the user
GET {{rootUrl}}/api/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiZWtoYW1hbDI2QGdtYWlsLmNvbSIsImlhdCI6MTc1NTYwMjAxOSwiZXhwIjoxNzU1NjAyOTE5fQ.N1bmPZZ-GJkyZgi0L7bT4qouzOj1rhEURTjppXnDmmY


###generating the otp
POST {{rootUrl}}/api/v1/auth/otp 
Content-Type: application/json

{
    "email": "bbekhamal26@gmail.com"
}

###reset password
POST {{rootUrl}}/api/v1/auth/reset-password
Content-Type: application/json

{
  "email": "bbekhamal26@gmail.com",
    "password": "Bibek@7",
      "otp":5088

}


###submit the bookings
POST {{rootUrl}}/api/v1/booking
Content-Type: application/json 

{
    "name": "John hamal Doe1  thing",
  "email": "john@email.com",
  "phone": "0400 111 222",
  "guests": 2,
  "date": "24/08/2025",
  "time": "19:30",
  "specialRequests": "Allergic to peanuts"
}

###submit the bookings for the members
POST {{rootUrl}}/api/v1/booking/members
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiZWtoYW1hbDI2QGdtYWlsLmNvbSIsImlhdCI6MTc1NjgxMzIwMiwiZXhwIjoxNzU2ODE0MTAyfQ.8C6TNKI19xRA4T7wXAkbVtC7MRD7GMMrjemSuzTxS_I


{
  "guests": 2,
  "date": "24/08/2025",
  "time": "19:30",
  "specialRequests": "Allergic to peanuts"
}


###fetching the user
GET {{rootUrl}}/api/v1/booking/members/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiZWtoYW1hbDI2QGdtYWlsLmNvbSIsImlhdCI6MTc1NjgxMzIwMiwiZXhwIjoxNzU2ODE0MTAyfQ.8C6TNKI19xRA4T7wXAkbVtC7MRD7GMMrjemSuzTxS_I


###fetching the menu
GET {{rootUrl}}/api/v1/menu


